#TODO: потом http глаголы прикрутить, по желанию
#thought API
create_thought:
  path: /thought/create/
  controller: Thought
  method: createThought

update_thought:
  path: /thought/update/
  controller: Thought
  method: updateThought

delete_thought:
  path: /thought/delete/
  controller: Thought
  method: deleteThought

#thought Content
thought_detail:
  path: /thought/{thoughtId}/
  controller: Thought
  method: getThoughtDetail

thought_list:
  path: /thought/
  controller: Thought
  method: getThoughtList

#tag API
create_tag:
  path: /tag/create/
  controller: Tag
  method: createTag
  defaults: { _controller: 'App\Controller\Tag::createTag' }

update_tag:
  path: /tag/update/
  controller: Tag
  method: updateTag

delete_tag:
  path: /tag/delete/
  controller: Tag
  method: deleteTag

#tag Content
tag_list:
  path: /tag/
  controller: Thought
  method: createThought
  defaults: { _controller: 'App\Controller\Tag::getTagList' }