# Идея такая 1ый уровень - название шаблона, 2-ой: путь к файлу шаблона и параметры, 3ий для параметров:
# сами параметры(названия, в шаблон передаваемые должен иметь такие же названия ключей массива) и значение по умолчанию, если какое то свойство не будет получено.
main_page:
  params:
    title: 'Главная страница'
  path: '/templates/main_page/template.php'
